var my_transportation = "These are my Favorite transportation.";
var travel_favorite = ["Cars", "Trains", "Bikes"];
var Bikes = "I would like to own a Honda motorcycle.";
var Cars = "I would like to own Kia spotage.";
var Trains = "I would like to travel in trains.";
console.log(my_transportation);
console.log(travel_favorite);
console.log(travel_favorite[0], "!", Cars);
console.log(travel_favorite[2], "!", Bikes);
console.log(travel_favorite[1], "!", Trains);
